from enum import Enum
from typing import Optional, Union, List, Dict
from pydantic import BaseModel, Field

class AnalysisOperation(str, Enum):
    COUNT = "COUNT"
    MEAN = "MEAN"
    MEDIAN = "MEDIAN"
    MIN = "MIN"
    MAX = "MAX"
    SUM = "SUM"
    STD = "STD"
    MISSING_VALUES = "MISSING_VALUES"
    UNIQUE_COUNT = "UNIQUE_COUNT"
    TOP_VALUES = "TOP_VALUES"
    GROUP_BY_MEAN = "GROUP_BY_MEAN"
    GROUP_BY_COUNT = "GROUP_BY_COUNT"
    CORRELATION = "CORRELATION"

class ConfidenceLevel(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"

class RecommendationPriority(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"

class AnalysisStep(BaseModel):
    step_id: str = Field(..., pattern=r"^step_[1-9]\d*$", description="Stable unique identifier for the step (e.g., step_1)")
    operation: AnalysisOperation = Field(..., description="The mathematical or structural operation to run")
    column: Optional[str] = Field(None, description="The primary target column for the operation")
    group_by: Optional[str] = Field(None, description="The grouping column for GROUP_BY operations")
    second_column: Optional[str] = Field(None, description="The second column for CORRELATION operations")
    limit: Optional[int] = Field(None, description="Enforced maximum limit of rows/values returned (e.g. for TOP_VALUES)")
    reason: Optional[str] = Field(None, description="The analytical rationale for performing this step")

# Type-safe structure for computed result instead of standard Any
ComputedResultType = Union[float, int, str, Dict[str, Union[float, int, str, None]], List[Union[float, int, str, Dict[str, Union[float, int, str, None]], None]], None]

class AnalysisResult(BaseModel):
    result_id: str = Field(..., pattern=r"^result_[1-9]\d*$", description="Stable deterministic identifier (e.g. result_1)")
    source_step_id: str = Field(..., pattern=r"^step_[1-9]\d*$", description="The step_id of the AnalysisStep that generated this result")
    operation: AnalysisOperation
    target_columns: List[str] = Field(default_factory=list, description="Columns involved in the analysis")
    computed_result: ComputedResultType = Field(None, description="Deterministic numerical, scalar or dictionary outputs of the computation")
    grouping_column: Optional[str] = Field(None, description="Column used for grouping if applicable")
    description: str = Field(..., description="Deterministic verification/explanation of the output")

class AnalysisPlan(BaseModel):
    objective: str = Field(..., description="Structured analytical objective for the task")
    steps: List[AnalysisStep] = Field(..., description="List of proposed deterministic steps to analyze the dataset")

class Finding(BaseModel):
    id: str = Field(..., pattern=r"^finding_[1-9]\d*$", description="Unique finding identifier (e.g., finding_1)")
    title: str = Field(..., description="Brief summary title of the finding")
    explanation: str = Field(..., description="Evidence-backed description of the observation")
    evidence_refs: List[str] = Field(..., description="List of result_id strings representing the evidence results supporting this finding")
    confidence: ConfidenceLevel = Field(..., description="Confidence rating of the finding")

class Recommendation(BaseModel):
    id: str = Field(..., pattern=r"^recommendation_[1-9]\d*$", description="Unique recommendation identifier (e.g., recommendation_1)")
    priority: RecommendationPriority = Field(..., description="Prioritized tier of the recommended action")
    action: str = Field(..., description="Proposed concrete business or operational step")
    rationale: str = Field(..., description="Justification explaining why this recommendation helps")
    finding_refs: List[str] = Field(..., description="List of finding_id strings linking back to the findings that support this action")

class ProviderReport(BaseModel):
    findings: List[Finding] = Field(..., description="Evidence-grounded observations generated by the LLM")
    limitations: List[str] = Field(..., description="Data limitations or caveats identified by the LLM")
    recommendations: List[Recommendation] = Field(..., description="Prioritized business recommendations linked to findings")
