from typing import List, Optional
from pydantic import BaseModel, Field
from app.models.analysis import AnalysisOperation, ConfidenceLevel, RecommendationPriority

class OllamaAnalysisStep(BaseModel):
    step_id: str = Field(..., description="Stable unique identifier for the step (e.g., step_1)")
    operation: AnalysisOperation = Field(..., description="The mathematical or structural operation to run")
    column: Optional[str] = Field(None, description="The primary target column for the operation")
    group_by: Optional[str] = Field(None, description="The grouping column for GROUP_BY operations")
    second_column: Optional[str] = Field(None, description="The second column for CORRELATION operations")
    limit: Optional[int] = Field(None, description="Enforced maximum limit of rows/values returned (e.g. for TOP_VALUES)")
    reason: Optional[str] = Field(None, description="The analytical rationale for performing this step")

class OllamaAnalysisPlan(BaseModel):
    objective: str = Field(..., description="Structured analytical objective for the task")
    steps: List[OllamaAnalysisStep] = Field(..., description="List of proposed deterministic steps to analyze the dataset")

class OllamaFinding(BaseModel):
    id: str = Field(..., description="Unique finding identifier (e.g., finding_1)")
    title: str = Field(..., description="Brief summary title of the finding")
    explanation: str = Field(..., description="Evidence-backed description of the observation")
    evidence_refs: List[str] = Field(..., description="List of result_id strings representing the evidence results supporting this finding")
    confidence: ConfidenceLevel = Field(..., description="Confidence rating of the finding")

class OllamaRecommendation(BaseModel):
    id: str = Field(..., description="Unique recommendation identifier (e.g., recommendation_1)")
    priority: RecommendationPriority = Field(..., description="Prioritized tier of the recommended action")
    action: str = Field(..., description="Proposed concrete business or operational step")
    rationale: str = Field(..., description="Justification explaining why this recommendation helps")
    finding_refs: List[str] = Field(..., description="List of finding_id strings linking back to the findings that support this action")

class OllamaProviderReport(BaseModel):
    findings: List[OllamaFinding] = Field(..., description="Evidence-grounded observations generated by the LLM")
    limitations: List[str] = Field(..., description="Data limitations or caveats identified by the LLM")
    recommendations: List[OllamaRecommendation] = Field(..., description="Prioritized business recommendations linked to findings")
